dirien/minectl

pgk/template/civo.sh.tmpl
pgk/template/cloud-config.yaml.tmpl

Update Minecraft Server Version (Java)  Fixes -> #16

Update Minecraft Server Version (Java)

---

docs/multi-server-monitoring-civo.md

Fix spelling errors in tutorial multi-server-monitoring-civo.md

---

README.md
cmd/minectl/list.go
config/bedrock/server-hetzner.yaml
config/java/server-hetzner.yaml
go.mod
go.sum
pgk/cloud/civo/civo.go
pgk/cloud/cloud.go
pgk/cloud/do/do.go
pgk/cloud/hetzner/hetzner.go
pgk/cloud/scaleway/scaleway.go
pgk/provisioner/provisioner.go

Add Hetzner as new cloud provider.

---

.github/workflows/ci.yaml
.gitignore
.pre-commit-config.yaml
Makefile
development.md
pgk/cloud/hetzner/hetzner.go

Rework on the Makefile and added golangci-lint

---

.gitignore
pgk/cloud/civo/civo.go
pgk/cloud/linode/linode.go
pgk/template/bash.tmpl
pgk/template/template.go
pgk/template/template_test.go

Mount Volume for Linode Server

---

config/bedrock/server-linode.yaml
config/java/server-linode.yaml
pgk/template/bash.tmpl
pgk/template/cloud-config.yaml.tmpl
pgk/template/template_test.go

update bedrock version -> 1.17.10.04

---

README.md
cmd/minectl/list.go

Add linode to docs and cli flag description

---

README.md

Add Linode and Hetzner libs to README.md

---

README.md
cmd/minectl/list.go
config/bedrock/server-equinix.yaml
config/java/server-equinix.yaml
go.mod
go.sum
pgk/cloud/equinix/equinix.go
pgk/provisioner/provisioner.go

New cloud provider - Equinix Metal

---

README.md
docs/getting-started-gce.md

Update Docs for GCE

---

README.md
config/bedrock/server-civo.yaml
config/bedrock/server-do.yaml
config/bedrock/server-equinix.yaml
config/bedrock/server-gce.yaml
config/bedrock/server-hetzner.yaml
config/bedrock/server-linode.yaml
config/bedrock/server-ovh.yaml
config/bedrock/server-scaleway.yaml
config/java/server-civo.yaml
config/java/server-do.yaml
config/java/server-equinix.yaml
config/java/server-gce.yaml
config/java/server-hetzner.yaml
config/java/server-linode.yaml
config/java/server-ovh.yaml
config/java/server-scaleway.yaml
docs/getting-started-civo-bedrock.md
docs/getting-started-civo.md
docs/getting-started-scaleway.md
go.mod
go.sum
pgk/manifest/schema.json
pgk/model/model.go
pgk/template/bash.tmpl
pgk/template/cloud-config.yaml.tmpl
pgk/template/template_test.go

Accept EULA should move into the MinecraftServer manifest

---

README.md
config/forge/server-do.yaml
pgk/manifest/schema.json
pgk/model/model.go
pgk/template/template_test.go
pgk/template/templates/bash/bash.tmpl
pgk/template/templates/bash/monitoring-binaries.tmpl
pgk/template/templates/bash/monitoring-files.tmpl
pgk/template/templates/cloud-init/cloud-config.yaml.tmpl
pgk/template/templates/cloud-init/monitoring-binaries.yaml.tmpl
pgk/template/templates/cloud-init/monitoring-files.yaml.tmpl

Make Promtheus monitoring configurable

---

pgk/cloud/civo/civo.go
pgk/cloud/do/do.go
pgk/cloud/equinix/equinix.go
pgk/cloud/gce/gce.go
pgk/cloud/hetzner/hetzner.go
pgk/cloud/linode/linode.go
pgk/cloud/ovh/ovh.go
pgk/cloud/scaleway/scaleway.go
pgk/template/template.go
pgk/update/server.go

Move update Minecraft server version to bash

---

README.md
cmd/minectl/create.go
cmd/minectl/plugins.go
pgk/automation/automation.go
pgk/cloud/civo/civo.go
pgk/cloud/do/do.go
pgk/cloud/equinix/equinix.go
pgk/cloud/gce/gce.go
pgk/cloud/hetzner/hetzner.go
pgk/cloud/linode/linode.go
pgk/cloud/ovh/ovh.go
pgk/cloud/scaleway/scaleway.go
pgk/provisioner/provisioner.go
pgk/update/server.go

Enable (basic) Plugin support

---

docs/running-minecraft-luckyblocks-budget-scaleway.md

Fix typo in running-minecraft-luckyblocks-budget-scaleway.md

---

.gitignore
README.md
cmd/minectl/create.go
cmd/minectl/delete.go
cmd/minectl/list.go
cmd/minectl/plugins.go
cmd/minectl/rcon.go
config/papermc/server-do.yaml
config/papermc/server-scaleway.yaml
go.mod
go.sum
pgk/automation/automation.go
pgk/cloud/civo/civo.go
pgk/cloud/do/do.go
pgk/cloud/equinix/equinix.go
pgk/cloud/gce/gce.go
pgk/cloud/hetzner/hetzner.go
pgk/cloud/linode/linode.go
pgk/cloud/ovh/ovh.go
pgk/cloud/scaleway/scaleway.go
pgk/model/model.go
pgk/provisioner/provisioner.go
pgk/rcon/rcon.go

Add RCON feature to minectl

---

README.md
config/java/server-vultr.yaml
config/papermc/server-vultr.yaml
go.mod
go.sum
pkg/cloud/cloud.go
pkg/cloud/vultr/vultr.go
pkg/provisioner/provisioner.go

New cloud provider - Vultr

---

pkg/cloud/hetzner/hetzner.go
pkg/provisioner/provisioner.go

Replace a status string for constant and remove newline

Replace a status string for constant and remove newline

---

README.md
cmd/minectl/list.go
config/bungeecord/proxy-civo.yaml
config/bungeecord/proxy-do.yaml
config/bungeecord/proxy-vultr.yaml
config/waterfall/proxy-do.yaml
config/waterfall/proxy-vultr.yaml
pkg/cloud/civo/civo.go
pkg/cloud/do/do.go
pkg/cloud/equinix/equinix.go
pkg/cloud/gce/gce.go
pkg/cloud/hetzner/hetzner.go
pkg/cloud/linode/linode.go
pkg/cloud/ovh/ovh.go
pkg/cloud/scaleway/scaleway.go
pkg/cloud/vultr/vultr.go
pkg/manifest/proxy.json
pkg/model/model.go
pkg/provisioner/provisioner.go
pkg/template/template.go
pkg/template/templates/bash/bungeecord-binary.tmpl
pkg/template/templates/bash/proxy-cloud-config.tmpl
pkg/template/templates/bash/rcon-proxy-binary.tmpl
pkg/template/templates/bash/waterfall-binary.tmpl
pkg/template/templates/cloud-init/bungeecord-binary.yaml.tmpl
pkg/template/templates/cloud-init/proxy-cloud-config.yaml.tmpl
pkg/template/templates/cloud-init/rcon-proxy-binary.yaml.tmpl
pkg/template/templates/cloud-init/waterfall-binary.yaml.tmpl
pkg/update/server.go

Add Suport for Proxy Server - bungeecord and waterfall

---

README.md
pkg/manifest/proxy.json
pkg/manifest/server.json
pkg/model/model.go
pkg/template/template_test.go
pkg/template/templates/bash/bash.tmpl
pkg/template/templates/bash/proxy-cloud-config.tmpl
pkg/template/templates/cloud-init/cloud-config.yaml.tmpl
pkg/template/templates/cloud-init/proxy-cloud-config.yaml.tmpl

Signed-off-by: Robert Igl <robert.igl@mail.schwarz>

Adds support for additional java options

---

.gitignore
config/waterfall/proxy-azure.yaml
pkg/model/model.go

Rework IsProxyServer function #102

---

.dockerignore
.github/workflows/ci.yaml
.goreleaser.yml
Dockerfile
cmd/minectl/minectl.go
go.sum
main.go

Provide minectl container (x64 and arm)

---

.github/workflows/ci.yaml
.goreleaser.yml
Dockerfile
README.md

Add UPX to minectl binary build

---

README.md
cmd/minectl/minectl.go

Explain headless mode in README.md

---

cmd/minectl/minectl.go
go.sum

Fix Dev Version String

---

go.sum
renovate.json

Add gomodTidy to renovatebot

---

README.md
go.mod
go.sum
pkg/cloud/oci/oci.go

Fix Lib version of oracle oci

---

.github/workflows/ci.yaml
.goreleaser.yml

Switch to goreleaser v0.176.0 container signing

---

.gitignore

Add cosign to gitignore

---

.gitignore
go.mod
go.sum

Add cosign to gitignore and update azure sdk

---

renovate.json

Disable Renovate dependency dashboard

---

.github/workflows/ci.yaml
go.mod
go.sum

Update go 1.17

---

go.sum
pkg/cloud/oci/oci.go

Update github.com/oracle/oci-go-sdk/v47 v47.0.0

---

.github/workflows/ci.yaml

chore: Update cosign

---

renovate.json

feat: Add semanticCommitTypeAll to renovate

---

config/nukkit/server-azure.yaml
config/nukkit/server-do.yaml
config/nukkit/server-gce.yaml
config/nukkit/server-ovh.yaml
pkg/cloud/civo/civo.go
pkg/cloud/oci/oci.go
pkg/provisioner/provisioner.go
pkg/template/template.go
pkg/template/template_test.go
pkg/template/templates/bash/bash.tmpl
pkg/template/templates/bash/nukkit-binary.tmpl
pkg/template/templates/cloud-init/cloud-config.yaml.tmpl
pkg/template/templates/cloud-init/nukkit-binary.yaml.tmpl
pkg/update/server.go

feat: Enable nukkitx support

---

pkg/cloud/azure/azure.go

chore: Update Azure Endpoints in SDK

---

.goreleaser.yml

fixes #119 
fixes #120 
fixes #196 

feat: Implement Linux apk,deb,rpm download enhancement

---

pkg/template/template.go
pkg/template/templates/bash/proxy-bash.tmpl

chore: fix template issue

---

config/powernukkit/server-azure.yaml
config/powernukkit/server-civo.yaml
pkg/cloud/civo/civo.go
pkg/cloud/oci/oci.go
pkg/provisioner/provisioner.go
pkg/template/template.go
pkg/template/template_test.go
pkg/template/templates/bash/bash.tmpl
pkg/template/templates/bash/powernukkit-binary.tmpl
pkg/template/templates/cloud-init/cloud-config.yaml.tmpl
pkg/template/templates/cloud-init/powernukkit-binary.yaml.tmpl
pkg/update/server.go

feat: Add PowerNukkit to minectl 🗺

---

config/nukkit/server-civo.yaml
config/papermc/server-scaleway.yaml
renovate.json

fix: add semanticCommits to renovate.json file

---

renovate.json

feat: add commitBody to renovate.json file

---

config/bedrock/server-civo.yaml
config/bedrock/server-do.yaml
config/bedrock/server-equinix.yaml
config/bedrock/server-gce.yaml
config/bedrock/server-hetzner.yaml
config/bedrock/server-linode.yaml
config/bedrock/server-oci.yaml
config/bedrock/server-ovh.yaml
config/bedrock/server-scaleway.yaml

chore: update bedrock versions in demo-config

---

README.md

docs: add GoFish install instruction to readme

---

README.md
cmd/minectl/list.go
cmd/minectl/minectl.go
cmd/minectl/wizard.go
go.mod
go.sum
pkg/cloud/cloud.go
pkg/manifest/server.json
pkg/model/model.go
pkg/template/template.go
pkg/template/template_test.go
pkg/template/templates/config/config.yaml.tmpl

feat: Build a wizard function into minectl 🗺

---

README.md

fix: docs for wizard function

---

.github/workflows/ci.yaml

fix: remove make all call in action

---

renovate.json

chore: add gomodUpdateImportPaths

---

config/papermc/server-scaleway.yaml
pkg/template/template_test.go
pkg/template/templates/bash/monitoring-binaries.tmpl
pkg/template/templates/cloud-init/monitoring-binaries.yaml.tmpl

chore: Update minecraft-exporter-prometheus version

---

README.md
config/velocity/proxy-do.yaml
config/velocity/proxy-gce.yaml
pkg/cloud/gce/gce.go
pkg/provisioner/provisioner.go
pkg/template/template.go
pkg/template/templates/bash/proxy-bash.tmpl
pkg/template/templates/bash/velocity-binary.tmpl
pkg/template/templates/cloud-init/proxy-cloud-config.yaml.tmpl
pkg/template/templates/cloud-init/velocity-binary.yaml.tmpl
pkg/update/server.go

feat: add support for velocity

---

config/java/server-aws.yaml
config/java/server-azure.yaml
config/java/server-civo.yaml
config/java/server-do.yaml
config/java/server-equinix.yaml
config/java/server-gce.yaml
config/java/server-hetzner.yaml
config/java/server-linode.yaml
config/java/server-oci.yaml
config/java/server-ovh.yaml
config/java/server-scaleway.yaml
config/java/server-vexxhost.yaml
config/java/server-vultr.yaml

chore: Update config to vanilla java version 1.18.1

---

config/java/server-aws.yaml
config/java/server-azure.yaml
config/java/server-civo.yaml
config/java/server-do.yaml
config/java/server-equinix.yaml
config/java/server-gce.yaml
config/java/server-hetzner.yaml
config/java/server-linode.yaml
config/java/server-oci.yaml
config/java/server-ovh.yaml
config/java/server-scaleway.yaml
config/java/server-vexxhost.yaml
config/java/server-vultr.yaml

chore: Update openjdk version to 17

---

README.md
config/java/server-aws-spot.yaml
config/java/server-azure-spot.yaml
config/java/server-gce-spot.yaml
pkg/cloud/aws/aws.go
pkg/cloud/azure/azure.go
pkg/cloud/gce/gce.go
pkg/manifest/server.json
pkg/model/model.go

feat: Enable Spot (Preemptible) Instances.

---

README.md

docs: add link to spot instance chapter

---

pkg/automation/automation.go
pkg/cloud/aws/aws.go
pkg/cloud/azure/azure.go
pkg/cloud/civo/civo.go
pkg/cloud/do/do.go
pkg/cloud/equinix/equinix.go
pkg/cloud/gce/gce.go
pkg/cloud/hetzner/hetzner.go
pkg/cloud/ionos/ionos.go
pkg/cloud/linode/linode.go
pkg/cloud/multipass/multipass.go
pkg/cloud/oci/oci.go
pkg/cloud/ovh/ovh.go
pkg/cloud/scaleway/scaleway.go
pkg/cloud/vexxhost/vexxhost.go
pkg/cloud/vultr/vultr.go
pkg/provisioner/provisioner.go

fix: typo in name of struct ResourceResults

---

config/papermc/server-aws.yaml
config/papermc/server-civo.yaml
config/papermc/server-do.yaml
config/papermc/server-ionos.yaml
config/papermc/server-linode.yaml
config/papermc/server-oci-arm.yaml
config/papermc/server-oci.yaml
config/papermc/server-scaleway.yaml
config/papermc/server-vexxhost.yaml
config/papermc/server-vultr.yaml
go.mod

chore: update papermc to > 1.18 version

---

config/bedrock/server-civo.yaml
config/bedrock/server-do.yaml
config/bedrock/server-equinix.yaml
config/bedrock/server-gce.yaml
config/bedrock/server-hetzner.yaml
config/bedrock/server-ionos.yaml
config/bedrock/server-linode.yaml
config/bedrock/server-oci.yaml
config/bedrock/server-ovh.yaml
config/bedrock/server-scaleway.yaml
config/bedrock/server-vexxhost.yaml

chore: update bedrock to > 1.18 version

---

config/craftbukkit/server-do.yaml
config/craftbukkit/server-linode.yaml
config/fabric/server-civo.yaml
config/fabric/server-do.yaml
config/fabric/server-linode.yaml
config/forge/server-do.yaml
config/forge/server-linode.yaml
config/spigot/server-azure.yaml
config/spigot/server-do.yaml
config/spigot/server-linode.yaml
internal/template/template_test.go
internal/template/templates/bash/fabric-binary.tmpl
internal/template/templates/cloud-init/fabric-binary.yaml.tmpl

chore: update fabric / forge / spigot / bukkuit to > 1.18 version

---

.github/workflows/lock.yml

feat: add lock-inactive support

---

config/papermc/server-vultr.yaml
internal/template/template_test.go
internal/template/templates/bash/monitoring-binaries.tmpl
internal/template/templates/cloud-init/monitoring-binaries.yaml.tmpl

chore: update all versions of the monitoring staack!

---

.github/workflows/ossf-scorecard-action.yaml

feat: add OSSF Scorecard Action

---

.goreleaser.yaml
README.md

feat: add ArtifactHub support for minectl image

---

.github/workflows/ci.yaml
.github/workflows/lock.yml
Dockerfile

feat: fix ossf scorecard findings for pining versions

---

.github/workflows/ci.yaml
.github/workflows/lock.yml
.github/workflows/ossf-scorecard-action.yaml

feat: add Harden Runner from step-security

---

cmd/minectl/delete.go
cmd/minectl/list.go
cmd/minectl/wizard.go
internal/cloud/azure/azure.go
internal/provisioner/provisioner.go
internal/template/template_test.go
internal/template/templates/bash/monitoring-binaries.tmpl
internal/template/templates/cloud-init/monitoring-binaries.yaml.tmpl

chore: update prometheus and minecraft-exporter

---

artifacthub-repo.yml

feat: add artifacthub-repo.yml

---

.github/workflows/ci.yaml
.github/workflows/lock.yml

feat: fix pipeline permissions

---

.github/workflows/ci.yaml
.github/workflows/lock.yml
.github/workflows/ossf-scorecard-action.yaml

feat: fix actions with renovate annotation

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature.yaml

feat: add bug and feature templates

---

.github/renovate.json

feat: add schedule and group support to renovate

---

.github/renovate.json

fixes https://github.com/dirien/minectl/issues/482

fix: renovate.json comma

---

.goreleaser.yaml

feat: change signing for docker to manifests

---

.github/workflows/ci.yaml
go.mod
go.sum

feat: update golang to version 1.18

---

internal/cloud/aws/aws.go
internal/cloud/multipass/multipass.go

feat: add some go 1.18 strings.cut

---

internal/cloud/aws/aws.go

fix: fix aws error on InstanceStatuses

---

config/papermc/server-aws.yaml
config/papermc/server-azure.yaml
config/papermc/server-civo.yaml
config/papermc/server-exoscale.yaml
config/papermc/server-fuga.yaml
config/papermc/server-hetzner.yaml
config/papermc/server-ionos.yaml
config/papermc/server-linode.yaml
config/papermc/server-oci-arm.yaml
config/papermc/server-oci.yaml
config/papermc/server-scaleway.yaml
config/papermc/server-vexxhost.yaml
config/papermc/server-vultr.yaml
internal/cloud/hetzner/hetzner.go

feat: Update Hetzner VM Image to 22.04

---

README.md
internal/cloud/aws/aws.go
internal/provisioner/provisioner.go

feat: Update AWS VM Image to 22.04

---

internal/cloud/azure/azure.go

feat: Upgrade Azure VM Image to 22.04

---

README.md
internal/cloud/do/do.go

feat: Upgrade DigitalOcean VM Image to 22.04

---

.github/renovate.json
go.mod
go.sum

feat: add egoscale to ignoreDeps in renovate

---

README.md
internal/cloud/equinix/equinix.go
internal/provisioner/provisioner.go

feat: Upgrade Equinix Metall VM Image to 22.04 and rename auth token

---

internal/cloud/gce/gce.go

feat: Upgrade GCE VM Image to 22.04 (minimal)

---

internal/cloud/fuga/fuga.go
internal/cloud/openstack/openstack.go
internal/cloud/vexxhost/vexxhost.go

feat: rename openshift to openstack :D

---

internal/cloud/exoscale/exoscale.go

feat: Upgrade Exosacle VM Image to 22.04

---

internal/cloud/fuga/fuga.go

feat: Upgrade Fuga Cloud VM Image to 22.04

---

internal/cloud/linode/linode.go

feat: Upgrade Linode VM Image to 22.04

---

README.md
internal/cloud/ovh/ovh.go

feat: Upgrade OVH VM Image to 22.04

---

internal/cloud/scaleway/scaleway.go

feat: Upgrade Scaleway VM Image to 22.04

---

internal/cloud/vultr/vultr.go

feat: Upgrade Vultr VM Image to 22.04

---

internal/template/template_test.go
internal/template/templates/bash/monitoring-binaries.tmpl
internal/template/templates/cloud-init/monitoring-binaries.yaml.tmpl

feat: update monitoring versions

---

internal/cloud/vultr/vultr.go

feat: remove deprecated Tag usage

---

README.md
config/java/server-azure.yaml
config/nukkit/server-azure.yaml
config/papermc/server-azure-arm.yaml
config/papermc/server-azure.yaml
config/papermc/server-oci-arm.yaml
config/powernukkit/server-azure.yaml
config/spigot/server-azure.yaml
config/waterfall/proxy-azure.yaml
internal/cloud/azure/azure.go
internal/cloud/oci/oci.go
internal/manifest/server.json
internal/model/model.go

feat: add arm field and enable Azure ARM support.

---

internal/cloud/civo/civo.go

feat: Upgrade Civo Cloud VM Image to 22.04

---

.goreleaser.yaml

feat: set mod_timestamp to ensure a build was reproducible

---

config/java/server-aws-spot.yaml
config/java/server-aws.yaml
config/java/server-azure-spot.yaml
config/java/server-azure.yaml
config/java/server-civo.yaml
config/java/server-do.yaml
config/java/server-equinix.yaml
config/java/server-exoscale.yaml
config/java/server-fuga.yaml
config/java/server-gce-spot.yaml
config/java/server-gce.yaml
config/java/server-hetzner.yaml
config/java/server-linode.yaml
config/java/server-oci.yaml
config/java/server-ovh.yaml
config/java/server-scaleway.yaml
config/java/server-vexxhost.yaml
config/java/server-vultr.yaml

feat: update Java Edition to 1.19

---

README.md

feat: add 1.19 logo to readme

---

internal/template/template_test.go
internal/template/templates/bash/bash.tmpl
internal/template/templates/bash/forge-binary.tmpl
internal/template/templates/cloud-init/cloud-config.yaml.tmpl
internal/template/templates/cloud-init/forge-binary.yaml.tmpl

feat: rework the installation of Forge server

---

config/bedrock/server-civo.yaml
config/craftbukkit/server-do.yaml
config/craftbukkit/server-linode.yaml
config/fabric/server-civo.yaml
config/fabric/server-do.yaml
config/fabric/server-linode.yaml
config/forge/server-civo.yaml
config/forge/server-do.yaml
config/forge/server-linode.yaml
config/multipass/server-java.yaml
config/multipass/server-papermc.yaml
config/papermc/server-aws.yaml
config/papermc/server-azure-arm.yaml
config/papermc/server-azure.yaml
config/papermc/server-civo.yaml
config/papermc/server-do.yaml
config/papermc/server-fuga.yaml
config/papermc/server-hetzner.yaml
config/papermc/server-ionos.yaml
config/papermc/server-linode.yaml
config/papermc/server-oci-arm.yaml
config/papermc/server-oci.yaml
config/papermc/server-scaleway.yaml
config/papermc/server-vexxhost.yaml
config/papermc/server-vultr.yaml
config/spigot/server-azure.yaml
config/spigot/server-do.yaml
config/spigot/server-linode.yaml

feat: enable 1.19 support for all mods

---

config/papermc/server-civo.yaml

fix: fix gamemode in server-civo.yaml

---

.github/workflows/lock.yml

feat: add permissions to lock workflow

---

config/java/server-gce-arm.yaml
config/papermc/server-gce-arm.yaml
internal/cloud/gce/gce.go

feat: enable GCP ARM support

---

README.md
cmd/minectl/wizard.go
config/purpur/server-aws-arm.yaml
config/purpur/server-aws.yaml
config/purpur/server-azure-arm.yaml
config/purpur/server-azure.yaml
config/purpur/server-civo.yaml
config/purpur/server-do.yaml
config/purpur/server-exoscale.yaml
config/purpur/server-fuga.yaml
config/purpur/server-gce-arm.yaml
config/purpur/server-hetzner.yaml
config/purpur/server-ionos.yaml
config/purpur/server-linode.yaml
config/purpur/server-oci-arm.yaml
config/purpur/server-oci.yaml
config/purpur/server-scaleway.yaml
config/purpur/server-vexxhost.yaml
config/purpur/server-vultr.yaml
internal/template/template.go
internal/template/template_test.go
internal/template/templates/bash/bash.tmpl
internal/template/templates/bash/purpur-binary.tmpl
internal/template/templates/cloud-init/cloud-config.yaml.tmpl
internal/template/templates/cloud-init/purpur-binary.yaml.tmpl
internal/update/server.go

feat: add purpur support

---

config/java/server-aws-arm.yaml
config/java/server-aws-spot.yaml
config/java/server-aws.yaml
config/java/server-azure-spot.yaml
config/java/server-azure.yaml
config/java/server-civo.yaml
config/java/server-do.yaml
config/java/server-equinix.yaml
config/java/server-exoscale.yaml
config/java/server-fuga.yaml
config/java/server-gce-arm.yaml
config/java/server-gce-spot.yaml
config/java/server-gce.yaml
config/java/server-hetzner.yaml
config/java/server-linode.yaml
config/java/server-oci.yaml
config/java/server-ovh.yaml
config/java/server-scaleway.yaml
config/java/server-vexxhost.yaml
config/java/server-vultr.yaml

chore: update java version to 1.19.1

---

config/purpur/server-aws-arm.yaml
config/purpur/server-aws.yaml
config/purpur/server-azure-arm.yaml
config/purpur/server-azure.yaml
config/purpur/server-civo.yaml
config/purpur/server-do.yaml
config/purpur/server-exoscale.yaml
config/purpur/server-fuga.yaml
config/purpur/server-gce-arm.yaml
config/purpur/server-hetzner.yaml
config/purpur/server-ionos.yaml
config/purpur/server-linode.yaml
config/purpur/server-oci-arm.yaml
config/purpur/server-oci.yaml
config/purpur/server-scaleway.yaml
config/purpur/server-vexxhost.yaml
config/purpur/server-vultr.yaml

chore: update purpur version to 1.19.1

---

config/papermc/server-aws-arm.yaml
config/papermc/server-aws.yaml
config/papermc/server-azure-arm.yaml
config/papermc/server-azure.yaml
config/papermc/server-civo.yaml
config/papermc/server-do.yaml
config/papermc/server-exoscale.yaml
config/papermc/server-fuga.yaml
config/papermc/server-gce-arm.yaml
config/papermc/server-hetzner.yaml
config/papermc/server-ionos.yaml
config/papermc/server-linode.yaml
config/papermc/server-oci-arm.yaml
config/papermc/server-oci.yaml
config/papermc/server-scaleway.yaml
config/papermc/server-vexxhost.yaml
config/papermc/server-vultr.yaml

chore: update papermc version to 1.19.1

---

config/craftbukkit/server-do.yaml
config/craftbukkit/server-linode.yaml
config/spigot/server-azure.yaml
config/spigot/server-do.yaml
config/spigot/server-linode.yaml

chore: update spigot and fabric version to 1.19.1

---

config/forge/server-civo.yaml
config/forge/server-do.yaml
config/forge/server-linode.yaml

chore: update forge version to 1.19.1

---

config/bedrock/server-aws.yaml
config/bedrock/server-civo.yaml
config/bedrock/server-do.yaml
config/bedrock/server-equinix.yaml
config/bedrock/server-exoscale.yaml
config/bedrock/server-gce.yaml
config/bedrock/server-hetzner.yaml
config/bedrock/server-ionos.yaml
config/bedrock/server-linode.yaml
config/bedrock/server-oci.yaml
config/bedrock/server-ovh.yaml
config/bedrock/server-scaleway.yaml
config/bedrock/server-vexxhost.yaml

chore: update bedrock version to 1.19.11.01

---

internal/cloud/oci/oci.go

feat: Upgrade OCI VM Image to 22.04

---

.github/workflows/ci.yaml

feat: update ci to go 1.19

---

config/bedrock/server-aws.yaml
config/bedrock/server-civo.yaml
config/bedrock/server-do.yaml
config/bedrock/server-equinix.yaml
config/bedrock/server-exoscale.yaml
config/bedrock/server-gce.yaml
config/bedrock/server-hetzner.yaml
config/bedrock/server-ionos.yaml
config/bedrock/server-linode.yaml
config/bedrock/server-oci.yaml
config/bedrock/server-ovh.yaml
config/bedrock/server-scaleway.yaml
config/bedrock/server-vexxhost.yaml
internal/cloud/aws/aws.go
internal/cloud/openstack/openstack.go
internal/template/template_test.go
internal/template/templates/bash/bedrock-binary.tmpl
internal/template/templates/cloud-init/bedrock-binary.yaml.tmpl

feat: update bedrock to 1.19.20.02

---

config/craftbukkit/server-do.yaml
config/craftbukkit/server-linode.yaml

feat: update craftbukkit to 1.19.2

---

Dockerfile

feat: switch to distroless base image

---

.github/workflows/fig.yaml
cmd/minectl/minectl.go
go.mod
go.sum

feat: add fig autocomplete support

---

Dockerfile
go.mod

feat: move to distroless:static image

---

.github/workflows/fig.yaml

chore: remove typo for fig autocomplete spec

---

README.md
cmd/minectl/create.go
cmd/minectl/delete.go
cmd/minectl/plugins.go
cmd/minectl/rcon.go
cmd/minectl/update.go
cmd/minectl/wizard.go

feat: rework cobra commands to support annotations

---

.github/renovate.json

feat: tune down noisy distroless update in renovate

---

cmd/minectl/create.go

Signed-off-by: Sahin Yort <thesayyn@gmail.com>

docs: fix typo

---

.github/dependabot.yml

feat: add dependabot to kick of renovate

---

.github/workflows/ossf-scorecard-action.yaml
README.md

feat: add ossf scorecard badge

---

README.md

feat: add ossf scorecard badge flat style

---

README.md

feat: add sonarcloud and openssf best pracrtices badge

---

.github/dependabot.yml
README.md

feat: add go reference

---

README.md

feat: add go report card badge

---

.github/workflows/lock.yml

feat: add GITHUB_TOKEN to lock flow

---

Dockerfile

feat: change base image to cgr.dev/chainguard/static

---

go.mod
go.sum

dep: update minectl-sdk

---

README.md
cmd/minectl/delete.go
config/java/server-scaleway.yaml

feat: add delete confirmation message and auto delete flag

---

go.mod
go.sum

feat: update minectl-sdk for Ubuntu 22 ARM on Azure

---

.github/workflows/lock.yml

feat: update breaking changes on lock-threads

---

.github/renovate.json

feat: remove renovate schedule

---

README.md

docs: add stargazer chart to README.md

---

config/bedrock/server-aws.yaml
config/bedrock/server-civo.yaml
config/bedrock/server-do.yaml
config/bedrock/server-equinix.yaml
config/bedrock/server-exoscale.yaml
config/bedrock/server-gce.yaml
config/bedrock/server-hetzner.yaml
config/bedrock/server-ionos.yaml
config/bedrock/server-linode.yaml
config/bedrock/server-oci.yaml
config/bedrock/server-ovh.yaml
config/bedrock/server-scaleway.yaml
config/bedrock/server-vexxhost.yaml

feat: update Minecraft bedrock config

---

config/java/server-aws-arm.yaml
config/java/server-aws-spot.yaml
config/java/server-aws.yaml
config/java/server-azure-spot.yaml

chore: rework demo config files

---

.github/workflows/ci.yaml
.goreleaser.yaml

feat: cosign everything in the release

---

.github/workflows/ci.yaml
.github/workflows/fig.yaml
go.mod

chore: update go version to 1.20.x

---

.goreleaser.yaml

feat: add - '-y' to goreleaser

---

.goreleaser.yaml

feat: update goreleaser to v2
